



troubleshooting 
OSError: dlopen(/usr/local/lib/libgdal.dylib, 6): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/lib/libgdal.dylib
  Reason: image not found

try :

brew reinstall jpeg gdal


raise GEOSException('Could not parse version info string "%s"' % ver)
django.contrib.gis.geos.error.GEOSException: Could not parse version info string "3.6.2-CAPI-1.10.2 4d2925d6"

try:

brew install spatialite-tools



File "/Applications/Qgis.app/Contents/Resources/python/reprlib/__init__.py", line 7, in <module>
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

use 
export PYTHONPATH=

export DJANGO_SETTINGS_MODULE=lampesCMS.settings.local
